<a href="https://colab.research.google.com/github/Brooklynn29/PyTorch_Tutorial/blob/main/Pytorch_tut_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
### random tensors


In [22]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.1+cu118


In [23]:
random_tensor = torch.rand(10,10)
random_tensor

tensor([[0.6287, 0.1607, 0.0141, 0.1725, 0.5892, 0.7300, 0.8884, 0.2370, 0.5324,
         0.3655],
        [0.4199, 0.5124, 0.9535, 0.3379, 0.5869, 0.7876, 0.6628, 0.7023, 0.6833,
         0.2131],
        [0.4716, 0.8298, 0.5444, 0.1168, 0.7206, 0.8188, 0.2645, 0.0574, 0.3577,
         0.3606],
        [0.0416, 0.3261, 0.8508, 0.1699, 0.8722, 0.6075, 0.2822, 0.8464, 0.0921,
         0.6781],
        [0.6154, 0.1622, 0.2482, 0.3239, 0.1847, 0.7821, 0.3805, 0.0508, 0.2156,
         0.0181],
        [0.7881, 0.4650, 0.0984, 0.3422, 0.2675, 0.2247, 0.5341, 0.6894, 0.8537,
         0.7216],
        [0.1114, 0.7711, 0.4458, 0.9790, 0.5125, 0.9814, 0.1930, 0.1992, 0.9815,
         0.4555],
        [0.1229, 0.4213, 0.1589, 0.3182, 0.4966, 0.5020, 0.1650, 0.2532, 0.7527,
         0.3844],
        [0.8939, 0.3274, 0.6051, 0.6528, 0.6963, 0.5266, 0.4132, 0.0046, 0.7103,
         0.4729],
        [0.7791, 0.3858, 0.8933, 0.6122, 0.1443, 0.9745, 0.4951, 0.3894, 0.8969,
         0.5508]])

In [24]:
random_tensor.ndim

2

In [25]:
# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3,224,224)) #colour channel(R,G,B), height , width
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [26]:
###zeros and ones

In [27]:
zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
#create a tensor of all ones
ones = torch.ones(5,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [29]:
ones.dtype


torch.float32

In [30]:
### creating a range of tensors

###Creating arange of tensors and tensors-like

In [31]:
# Use torch.range
one_to_ten = torch.arange(0,11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
one_to_thousand = torch.arange(0,1000,step=29)
one_to_thousand
## can also use torch.arange(start=0,end=100,step=29)


tensor([  0,  29,  58,  87, 116, 145, 174, 203, 232, 261, 290, 319, 348, 377,
        406, 435, 464, 493, 522, 551, 580, 609, 638, 667, 696, 725, 754, 783,
        812, 841, 870, 899, 928, 957, 986])

In [33]:
#Creating tensors_like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes
 Note: tensor datatypes is one of the 3 big issues/errors with Pytorch and DL you'll run into
 1. Tensors not right datatype
 2. Tensors not right shape
 3. Tensors not on right device

In [34]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype =None,#what datatype is the tensor(eg. float32 or float 16)
                               device=None, # can set to cpu or gpu("cpu","cuda")
                               requires_grad=False) #whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [35]:
float_32_tensor.dtype

torch.float32

In [36]:

#Coverting the float32 tensor to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [38]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [39]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors(Getting Attributes)
1. Tensors not right datatype - to do ger datatype from a tensor, cab use tensor.dtype
2. Tensors not right shape - to get from tensor, can use tensor.shape
3. Tensors not on right device - to get device from trensor, can use tensor.device


In [40]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0688, 0.1622, 0.2406, 0.3733],
        [0.8104, 0.7118, 0.5571, 0.7309],
        [0.0052, 0.5336, 0.6613, 0.6829]])

In [41]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [42]:
some_tensor.size()

torch.Size([3, 4])

In [43]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Devive tensor is on:{some_tensor.device}")

tensor([[0.0688, 0.1622, 0.2406, 0.3733],
        [0.8104, 0.7118, 0.5571, 0.7309],
        [0.0052, 0.5336, 0.6613, 0.6829]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Devive tensor is on:cpu


 ### Manipulating Tensors (tensor operations)

 tensor operations include :
 * Addition
 * Subtraction
 * Multiplication(element wise)
 * Division
 * Matrix Multiplication

In [44]:
#Create a tensor
tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [45]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [46]:
#Substract by 10
tensor-10

tensor([-9, -8, -7])

In [47]:
#trying out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [48]:
torch.add(tensor,29)

tensor([30, 31, 32])

from traitlets import dlink
### Matrix Multiplication

* Two main ways in neural networks and DL
1. element wise mul
2. Matrix Mul(dot product)

there are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* '(3,2) @ (3,2)' won't work
* '(2,3) @ (3,2)' will work
* '(3,2) @ (2,3)' will work

2. The resulting matrix has the shape of the outer dimensions:
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)


In [49]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.6544, 0.1337],
        [1.2200, 0.7067]])

In [50]:
torch.matmul(torch.rand(3,10), torch.rand(10,3))

tensor([[2.5469, 3.1985, 1.7483],
        [2.1724, 2.7887, 1.3674],
        [2.4588, 2.6006, 2.4126]])

In [51]:
#Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [52]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [53]:
 1*1+2*2+3*3

14

In [54]:
tensor @ tensor

tensor(14)

In [55]:
%%time
value=0
for i in range (len(tensor)):
  value+=tensor[i] * tensor[i]
  print(value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 3.8 ms, sys: 992 µs, total: 4.79 ms
Wall time: 5.72 ms


In [56]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 925 µs, sys: 90 µs, total: 1.02 ms
Wall time: 953 µs


tensor(14)

### One of the most common error in deep leraning : shape errors

In [58]:
#Shapes for Matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A,tensor_B) #torch.mm is th same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A,tensor_B)

RuntimeError: ignored

In [59]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

#To fix our tensor shape issue, we can manipulate the shape of one of our tensors using a *transpose*
A transpose switches the axes of dimensions of a given tensor

In [60]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [61]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [62]:
# The matrix multiplication operationworks when tebsor_B is transposed
print(f"Original shapes: tebsor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes : tebsor_A = {tensor_A.shape}(same as above), tensor_B = {tensor_B.T}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tebsor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes : tebsor_A = torch.Size([3, 2])(same as above), tensor_B = tensor([[ 7,  8,  9],
        [10, 11, 12]])
Multiplying: torch.Size([3, 2]) @ tensor([[ 7,  8,  9],
        [10, 11, 12]]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [63]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

### Finding the min,max,mean,sum,etc(tensor aggregation)

In [64]:
#Create a tensor
x= torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [65]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [66]:
#Find the max
torch.max(x) , x.max()

(tensor(91), tensor(91))

In [67]:
#Find the mean
torch.mean(x.type(torch.float32))

tensor(46.)

In [68]:
x.type(torch.float32).mean()

tensor(46.)

In [69]:
#Find the sum
torch.sum(x) , x.sum()

(tensor(460), tensor(460))

###Finding the positional min and max

In [70]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [71]:
# Finds the position in tensor that has the minimum value with argmin() -> returns index position of target where the minimum value occurs
x.argmin()

tensor(0)

In [72]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [73]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking -  Combine multiple tensors on top of eah other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions to a target tensor
* Unsqueeze - Add '1' dimension. to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way


In [74]:
#Lets create a tensor
import torch
x= torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [75]:
#Add an exta dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [76]:
#Change the view
z= x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
#Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [78]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x] , dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [79]:
#torch.squeeze () - removes all single dimensions from a target tensor
print(f"Previous tensor :{x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New shape :{x_squeezed.shape}")


Previous tensor :tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape : torch.Size([1, 9])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape :torch.Size([9])


In [80]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target :{x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor :{x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target :tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor :tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [81]:
x_reshaped.squeeze().shape

torch.Size([9])

In [82]:
#torch.permute - rearranges the dimesions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[Height,Width,colour_channels]
#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}") # [colour_channels, height,width]


Previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [83]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

###Indexing(selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [84]:
#Create a tensor
import torch
x= torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [85]:
#Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [86]:
#Lets index on middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [87]:
#lets index on most inner bracket
x[0][0][0]

tensor(1)

In [88]:
#You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [89]:
#Get all values of Oth and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [90]:
#Get all values of the 0 dimension but only 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [91]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [92]:
#Index on x to return 9
x[0,2,2]



tensor(9)

In [93]:
#Index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

In [94]:
x[0,2]

tensor([7, 8, 9])

In [95]:
x[:,:,0]

tensor([[1, 4, 7]])