<a href="https://colab.research.google.com/github/Brooklynn29/PyTorch_Tutorial/blob/main/PyTroch_tut_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor-> torch.from_numpy(ndarray)
* PyTorch tensor ->NumPy-> torch.Tensor.numpy()

In [ ]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning : when converting from numpy ->pytorch, pytorch reflects numpy's defauly datatype of float64 specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Change the value of array, what will this do to the tensor?
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor, what happpens to 'numpy_tensor'?
tensor = tensor + 1
tensor,numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibility (tryping to take random out if random)

In short how a neural network learns

'start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data ->again ->again -> againnn...'

To reduce the randomness in neural networks and Pytorch comes the concept of a **random seed.**

Essentially what the **random seed** does is "flavour" the randomness

In [ ]:
import torch
#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8711, 0.9721, 0.8675, 0.6209],
        [0.0932, 0.7639, 0.6143, 0.2754],
        [0.6837, 0.5208, 0.4551, 0.6700]])
tensor([[0.1153, 0.1161, 0.0439, 0.0165],
        [0.0672, 0.4437, 0.0702, 0.0822],
        [0.1029, 0.3124, 0.7824, 0.6559]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Lets make some random but reproducibile tensors
import torch

#Set the random seed
RANDOM_SEED =42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#Extra resources for reproducibility
* https://pytorch.org/docs/stable/notes/randomness.html

##Running tensors and and Pytorch objects on the GPUs (and making faster computatiions)

GPUs = faster computation on numbers, thanks to CUDA + PyTroch working behind the scenes to make everything good

### Getting a GPU
IF you want to use your own gpu ( your devices gpu ) then for this refer to PyTroch setup documentation

In [ ]:
!nvidia-smi

Wed Aug  2 13:54:19 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Check for gpu access with PyTroch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models  ) on the gpu
the reason we want out tensors /models on the GPU is beacause using a gpu results in faster computations.

In [ ]:
#Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
#If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
#To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')